# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Example Workflow

on:
  workflow_run:
    workflows:
      - 'Build and Test'
    types:
      - requested
      - completed

jobs:
  example-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Run Example Command
        run: echo "Running example command"



         
